version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    image: hy1358783794/retail-management:liangsen
    container_name: retail-management
    restart: always
    ports:
      - '97664:80'
    environment:
      - NODE_ENV=production
    networks:
      - retail-network

networks:
  retail-network:
    driver: my_bridge_network
